'use strict';
/**
 * MixLens Final Mastering Analysis 1.0 — Professional TXT report.
 */

(function (root, factory) {
  if (typeof module === 'object' && module.exports) {
    module.exports = factory(require('./utilities'), require('./platform-profiles'));
  } else {
    root.MATxt = factory(root.MAUtilities, root.MAPlatformProfiles);
  }
}(typeof self !== 'undefined' ? self : this, function (U, Profiles) {

  function kv(label, value) {
    return label + ': ' + (value == null || value === '' ? 'Not available' : String(value));
  }

  function buildTextReport(json) {
    const f = json.file || {};
    const t = json.technical || {};
    const ex = json.executive_summary || {};
    const qc = json.qc_score || {};
    const L = [];
    L.push('MIXLENS FINAL MASTERING ANALYSIS');
    L.push('==========================================');
    L.push('FINAL MASTERING ANALYSIS ' + json.engine_version);
    L.push('Professional Mastering QC & Platform Delivery Analyzer');
    L.push('Local DSP Mastering Analysis Engine');
    L.push('100% LOCAL DSP ANALYSIS');
    L.push('Your audio stays on your device.');
    if (json.demo) L.push('DEMO DATA');
    L.push('');
    L.push(kv('FILE', f.name));
    L.push(kv('FORMAT', f.format));
    L.push(kv('SAMPLE RATE', f.sample_rate ? (f.sample_rate / 1000) + ' kHz' : null));
    L.push(kv('BIT DEPTH', f.bit_depth));
    L.push(kv('CHANNELS', f.channel_layout || f.channels));
    L.push(kv('DURATION', f.duration_label || f.duration_seconds));
    L.push(kv('ANALYZED', json.analysis_timestamp));
    L.push('');
    L.push('------------------------------------------');
    L.push('01. EXECUTIVE SUMMARY');
    L.push('------------------------------------------');
    L.push(kv('FINAL MASTER QC', qc.score != null ? qc.score + '/100' : null));
    L.push(kv('DELIVERY STATUS', json.delivery_status || (ex.delivery_status)));
    L.push('');
    L.push('Major Findings:');
    (ex.major_findings || []).forEach(function (x) { L.push(x); });
    L.push('');
    if (ex.text) { L.push(ex.text); L.push(''); }
    L.push('------------------------------------------');
    L.push('02. FILE INFORMATION');
    L.push('------------------------------------------');
    L.push(kv('Filename', f.name));
    L.push(kv('File size', f.size_label));
    L.push(kv('Duration', f.duration_label));
    L.push(kv('Musical content duration', json.silence && json.silence.musical_content_duration_seconds != null ? json.silence.musical_content_duration_seconds + ' s' : null));
    L.push(kv('Sample rate', f.sample_rate));
    L.push(kv('Channels', f.channels));
    L.push(kv('Channel layout', f.channel_layout));
    L.push(kv('Master format', json.master_format && json.master_format.label));
    L.push(kv('Sample count', f.sample_count));
    L.push(kv('Codec', f.codec));
    L.push(kv('Bit depth', f.bit_depth));
    L.push(kv('Format', f.format));
    L.push('');
    L.push('------------------------------------------');
    L.push('03. TECHNICAL INTEGRITY');
    L.push('------------------------------------------');
    L.push(kv('Sample Peak', t.sample_peak_dbfs != null ? t.sample_peak_dbfs + ' dBFS' : null));
    L.push(kv('Estimated True Peak', t.true_peak_dbtp != null ? t.true_peak_dbtp + ' dBTP' : null));
    L.push(kv('RMS', t.rms_dbfs != null ? t.rms_dbfs + ' dBFS' : null));
    L.push(kv('Integrated Loudness', t.integrated_lufs != null ? t.integrated_lufs + ' LUFS' : null));
    L.push(kv('Crest Factor', t.crest_factor_db != null ? t.crest_factor_db + ' dB' : null));
    L.push(kv('DC Offset', t.dc_offset != null ? t.dc_offset : null));
    L.push(kv('Headroom', t.headroom_db != null ? t.headroom_db + ' dB' : null));
    L.push(kv('Clipping', json.clipping && json.clipping.classification));
    L.push(kv('Technical status', t.status));
    L.push('');
    L.push('------------------------------------------');
    L.push('04. LOUDNESS ANALYSIS');
    L.push('------------------------------------------');
    const ld = json.loudness || {};
    L.push(kv('Integrated', ld.integrated_lufs != null ? ld.integrated_lufs + ' LUFS' : null));
    L.push(kv('Short-Term Maximum', ld.short_term_max_lufs != null ? ld.short_term_max_lufs + ' LUFS' : null));
    L.push(kv('Momentary Maximum', ld.momentary_max_lufs != null ? ld.momentary_max_lufs + ' LUFS' : null));
    L.push(kv('Short-term median', ld.short_term_median_lufs != null ? ld.short_term_median_lufs + ' LUFS' : null));
    L.push(kv('LRA', ld.lra_lu != null ? ld.lra_lu + ' LU' : null));
    L.push(kv('Method', ld.method));
    L.push(kv('Confidence', ld.confidence));
    if (ld.loudest_section) L.push(kv('Loudest section', U.fmtTime(ld.loudest_section.time_s) + '  ' + ld.loudest_section.lufs + ' LUFS'));
    if (ld.quietest_section) L.push(kv('Quietest section', U.fmtTime(ld.quietest_section.time_s) + '  ' + ld.quietest_section.lufs + ' LUFS'));
    L.push('');
    L.push('------------------------------------------');
    L.push('05. TRUE PEAK ANALYSIS');
    L.push('------------------------------------------');
    const tp = json.true_peak || {};
    L.push(kv('Estimated True Peak', tp.value_dbtp != null ? tp.value_dbtp + ' dBTP' : null));
    L.push(kv('Timestamp', tp.timestamp_s != null ? U.fmtTime(tp.timestamp_s) : null));
    L.push(kv('Events above −1 dBTP (count)', tp.event_count));
    L.push(kv('Sample Peak', tp.sample_peak_dbfs != null ? tp.sample_peak_dbfs + ' dBFS' : null));
    L.push(kv('Inter-sample difference', tp.inter_sample_difference_db != null ? tp.inter_sample_difference_db + ' dB' : null));
    const pa = json.platform_analysis || {};
    L.push(kv('Selected Reference', pa.true_peak_reference_dbtp != null ? pa.true_peak_reference_dbtp + ' dBTP' : null));
    L.push(kv('Difference vs reference', pa.true_peak_difference_db != null ? pa.true_peak_difference_db + ' dB' : null));
    L.push(kv('Status', pa.true_peak_status));
    L.push('Label: ESTIMATED TRUE PEAK (4× interpolation).');
    L.push('');
    L.push('------------------------------------------');
    L.push('06. CLIPPING ANALYSIS');
    L.push('------------------------------------------');
    const cl = json.clipping || {};
    L.push(kv('Status', cl.status));
    L.push(kv('Classification', cl.classification));
    L.push(kv('Events', cl.event_count));
    L.push(kv('First Event', cl.first_event_s != null ? U.fmtTime(cl.first_event_s) : 'None'));
    L.push(kv('Maximum Consecutive Samples', cl.maximum_consecutive_samples));
    L.push(kv('Clipped sample %', cl.clipping_percent));
    if (cl.evidence) L.push('Evidence: ' + cl.evidence);
    L.push('');
    L.push('------------------------------------------');
    L.push('07. DYNAMICS ANALYSIS');
    L.push('------------------------------------------');
    const d = json.dynamics || {};
    L.push(kv('Crest Factor', d.crest_factor_db != null ? d.crest_factor_db + ' dB' : null));
    L.push(kv('Peak-to-Loudness', d.peak_to_loudness_ratio_db != null ? d.peak_to_loudness_ratio_db + ' dB' : null));
    L.push(kv('LRA', d.lra_lu != null ? d.lra_lu + ' LU' : null));
    L.push(kv('Dynamic Range Estimate', d.dynamic_range_estimate_db != null ? d.dynamic_range_estimate_db + ' dB' : null));
    L.push(kv('Dynamic Character', d.dynamic_character));
    if (d.crest_factor_note) L.push(d.crest_factor_note);
    if (d.evidence) L.push('Evidence: ' + d.evidence);
    if (json.loudness_peak_correlation && json.loudness_peak_correlation.note) {
      L.push('Loudness/peak correlation: ' + json.loudness_peak_correlation.note);
    }
    L.push('');
    L.push('------------------------------------------');
    L.push('08. FREQUENCY ANALYSIS');
    L.push('------------------------------------------');
    const sp = json.spectrum || {};
    L.push(kv('Centroid', sp.centroid_hz != null ? sp.centroid_hz + ' Hz' : null));
    L.push(kv('Spread', sp.spread_hz != null ? sp.spread_hz + ' Hz' : null));
    L.push(kv('Rolloff (85%)', sp.rolloff_hz != null ? sp.rolloff_hz + ' Hz' : null));
    L.push(kv('Flatness', sp.flatness));
    L.push(kv('Flux', sp.flux));
    L.push(kv('Spectral density', sp.spectral_density));
    L.push(kv('Low-frequency energy', sp.low_frequency_energy_percent != null ? sp.low_frequency_energy_percent + '%' : null));
    L.push(kv('Midrange energy', sp.midrange_energy_percent != null ? sp.midrange_energy_percent + '%' : null));
    L.push(kv('High-frequency energy', sp.high_frequency_energy_percent != null ? sp.high_frequency_energy_percent + '%' : null));
    (sp.extremes || []).forEach(function (e) { L.push('· ' + e.statement); });
    L.push('');
    L.push('------------------------------------------');
    L.push('09. TONAL BALANCE');
    L.push('------------------------------------------');
    if (sp.baseline_note) L.push(sp.baseline_note);
    (sp.groups || []).forEach(function (g) {
      L.push(g.name.toUpperCase() + '  ' + g.frequency_range_hz[0] + '–' + g.frequency_range_hz[1] + ' Hz  ' + g.energy_percent + '%');
    });
    L.push('');
    (sp.regions || []).forEach(function (z) {
      L.push(z.name + '  energy ' + z.energy_percent + '%  pink-share ' + z.expected_pink_percent + '%  ' + z.status);
    });
    L.push('');
    L.push('------------------------------------------');
    L.push('10. STEREO ANALYSIS');
    L.push('------------------------------------------');
    const st = json.stereo || {};
    if (!st.applicable) L.push(st.note || 'Mono master.');
    else {
      L.push(kv('L RMS', st.l_rms_dbfs != null ? st.l_rms_dbfs + ' dBFS' : null));
      L.push(kv('R RMS', st.r_rms_dbfs != null ? st.r_rms_dbfs + ' dBFS' : null));
      L.push(kv('L Peak', st.l_peak_dbfs != null ? st.l_peak_dbfs + ' dBFS' : null));
      L.push(kv('R Peak', st.r_peak_dbfs != null ? st.r_peak_dbfs + ' dBFS' : null));
      L.push(kv('Correlation', st.correlation));
      L.push(kv('Stereo Width', st.stereo_width_label + ' (' + st.stereo_width_percent + '% side)'));
      L.push(kv('Mid energy', st.mid_energy_dbfs != null ? st.mid_energy_dbfs + ' dBFS' : null));
      L.push(kv('Side energy', st.side_energy_dbfs != null ? st.side_energy_dbfs + ' dBFS' : null));
    }
    L.push('');
    L.push('------------------------------------------');
    L.push('11. PHASE ANALYSIS');
    L.push('------------------------------------------');
    const ph = json.phase || {};
    L.push(kv('Correlation', ph.correlation));
    L.push(kv('Interpretation', ph.interpretation));
    L.push(kv('Status', ph.status));
    (ph.bands || []).forEach(function (b) {
      L.push(b.name + ': ' + b.correlation + '  ' + b.status);
    });
    L.push('');
    L.push('------------------------------------------');
    L.push('12. MONO COMPATIBILITY');
    L.push('------------------------------------------');
    const mo = json.mono_compatibility || {};
    L.push(kv('Rating', mo.rating));
    L.push(kv('Energy ratio', mo.energy_ratio));
    L.push(kv('Status', mo.status));
    if (mo.note) L.push(mo.note);
    L.push('');
    L.push('------------------------------------------');
    L.push('13. CHANNEL BALANCE');
    L.push('------------------------------------------');
    const cb = json.channel_balance || {};
    L.push(kv('Left RMS', cb.l_rms_dbfs));
    L.push(kv('Right RMS', cb.r_rms_dbfs));
    L.push(kv('Difference', cb.lr_balance_db != null ? cb.lr_balance_db + ' dB' : null));
    L.push(kv('Status', cb.status));
    L.push('');
    L.push('------------------------------------------');
    L.push('14. DC OFFSET');
    L.push('------------------------------------------');
    const dc = json.dc_offset || {};
    L.push(kv('Mean sample', dc.mean));
    L.push(kv('Absolute', dc.absolute));
    L.push(kv('dBFS', dc.dbfs != null ? dc.dbfs + ' dBFS' : null));
    L.push(kv('Status', dc.severity));
    if (dc.evidence) L.push(dc.evidence);
    L.push('');
    L.push('------------------------------------------');
    L.push('15. SILENCE / FADE ANALYSIS');
    L.push('------------------------------------------');
    const sil = json.silence || {};
    const fade = json.fade || {};
    L.push(kv('Leading Silence', sil.leading_seconds != null ? sil.leading_seconds + ' sec' : null));
    L.push(kv('Trailing Silence', sil.trailing_seconds != null ? sil.trailing_seconds + ' sec' : null));
    L.push(kv('Internal Silence', sil.internal_count ? (sil.internal_count + ' events') : 'None'));
    L.push(kv('Noise floor', sil.noise_floor_dbfs != null ? sil.noise_floor_dbfs + ' dBFS (' + sil.noise_floor_confidence + ')' : sil.noise_floor_confidence));
    L.push(kv('Fade-In', fade.fade_in && fade.fade_in.present ? ('Present' + (fade.fade_in.duration_s != null ? ' (' + fade.fade_in.duration_s + ' s)' : '')) : (fade.fade_in && fade.fade_in.shape)));
    L.push(kv('Fade-Out', fade.fade_out && fade.fade_out.present ? ('Present' + (fade.fade_out.duration_s != null ? ' (' + fade.fade_out.duration_s + ' s)' : '')) : (fade.fade_out && fade.fade_out.shape)));
    L.push(kv('Starting', fade.starting));
    L.push(kv('Ending', fade.ending));
    L.push('');
    L.push('------------------------------------------');
    L.push('16. DISTORTION INDICATORS');
    L.push('------------------------------------------');
    const dist = json.distortion || {};
    L.push(kv('Summary', dist.summary));
    L.push(kv('Confidence', dist.confidence));
    (dist.indicators || []).forEach(function (i) { L.push('· [' + i.confidence + '] ' + i.statement); });
    if (dist.note) L.push(dist.note);
    L.push('');
    L.push('------------------------------------------');
    L.push('17. PLATFORM DELIVERY ANALYSIS');
    L.push('------------------------------------------');
    L.push(kv('Selected Platform', pa.platform_name));
    L.push(kv('Measured Loudness', pa.measured_lufs != null ? pa.measured_lufs + ' LUFS' : null));
    L.push(kv('Platform Reference', pa.loudness_reference_lufs != null ? pa.loudness_reference_lufs + ' LUFS (REFERENCE)' : 'No loudness reference (this profile)'));
    L.push(kv('Difference', pa.loudness_difference_lu != null ? pa.loudness_difference_lu + ' LU' : null));
    L.push(kv('Estimated True Peak', pa.measured_true_peak_dbtp != null ? pa.measured_true_peak_dbtp + ' dBTP' : null));
    L.push(kv('True Peak Reference', pa.true_peak_reference_dbtp != null ? pa.true_peak_reference_dbtp + ' dBTP (REFERENCE)' : null));
    L.push(kv('Status', pa.status));
    if (pa.normalization_note) L.push(pa.normalization_note);
    if (pa.disclaimer) L.push(pa.disclaimer);
    L.push('');
    L.push('------------------------------------------');
    L.push('18. PLATFORM COMPARISON');
    L.push('------------------------------------------');
    L.push('One master may be delivered to multiple platforms. Separate masters are not implied.');
    (json.platform_comparison || []).forEach(function (row) {
      L.push('');
      L.push(row.platform_name);
      L.push('Measured: ' + (row.measured_lufs != null ? row.measured_lufs + ' LUFS' : 'n/a'));
      L.push('Reference: ' + (row.loudness_reference_lufs != null ? row.loudness_reference_lufs + ' LUFS (configured)' : 'none'));
      L.push('Difference: ' + (row.loudness_difference_lu != null ? row.loudness_difference_lu + ' LU' : 'n/a'));
      L.push('True Peak: ' + (row.measured_true_peak_dbtp != null ? row.measured_true_peak_dbtp + ' dBTP' : 'n/a'));
      L.push('Status: ' + row.status);
    });
    L.push('');
    L.push('------------------------------------------');
    L.push('19. CUSTOM TARGET ANALYSIS');
    L.push('------------------------------------------');
    const ct = json.custom_target || {};
    if (!ct.enabled) L.push('No custom file-format constraints evaluated beyond the Custom platform profile.');
    else {
      L.push(kv('Status', ct.status));
      (ct.findings || []).forEach(function (x) { L.push('· ' + x); });
    }
    L.push('');
    L.push('------------------------------------------');
    L.push('20. QC SCORE');
    L.push('------------------------------------------');
    L.push(kv('FINAL MASTER QC', qc.score != null ? qc.score + '/100' : null));
    if (qc.weights_note) L.push(qc.weights_note);
    const br = qc.breakdown || {};
    Object.keys(br).forEach(function (k) {
      const b = br[k];
      L.push(k + ': ' + b.score + '/100  (weight ' + b.weight + ')');
      (b.deductions || []).forEach(function (d0) {
        L.push('  −' + d0.points + '  ' + d0.reason);
      });
    });
    L.push('');
    L.push('------------------------------------------');
    L.push('21. DELIVERY STATUS');
    L.push('------------------------------------------');
    L.push(json.delivery_status || 'Not available');
    (qc.positives || []).forEach(function (x) { L.push('✓ ' + x); });
    (qc.issues || []).forEach(function (x) { L.push('⚠ ' + x); });
    L.push('');
    L.push('------------------------------------------');
    L.push('22. ENGINEERING OBSERVATIONS');
    L.push('------------------------------------------');
    (json.engineering_observations || []).forEach(function (o, i) {
      L.push((i + 1) + '. MEASUREMENT: ' + o.measurement);
      L.push('   EVIDENCE: ' + o.evidence);
      L.push('   INTERPRETATION: ' + o.interpretation);
      L.push('   ENGINEERING OBSERVATION: ' + o.engineering_observation);
      L.push('');
    });
    L.push('These observations are analytical only and do not constitute automatic mastering instructions.');
    L.push('');
    L.push('------------------------------------------');
    L.push('23. RAW MEASUREMENTS');
    L.push('------------------------------------------');
    L.push('See the companion JSON export for the full numeric payload');
    L.push('(schema_version ' + json.schema_version + ', engine_version ' + json.engine_version + ').');
    L.push('');
    L.push(json.disclaimer || Profiles.DISCLAIMER);
    L.push('');
    L.push('==========================================');
    L.push('END OF REPORT');
    L.push('==========================================');
    return L.join('\n');
  }

  return { buildTextReport: buildTextReport };
}));
